### ISSUE TITLE
Having issues downloading the modpack

### ISSUE THREAD

**Issue by Santereva** [AllTheMods/All-the-mods-7-Sky#341]
I have done/attempted to download the modpack via the curseforge app and manually on the curseforge website, but I am not getting any of the mods from the manual install and the curseforge app keeps deleting the pack during install.

When downloading via the app, I notice that it doesn't download any mods and goes straight to patching. It's during the patching is when it just deletes itself.

Can anyone explain why?

**Comment by Mitchell5200** [comment]
Try in the top right three dot menu, the option "Repair Installation", that should fix it

**Comment by Santereva** [comment]
> Try in the top right three dot menu, the option "Repair Installation", that should fix it

I can't do that if I can't even download the mod pack to begin with. You need to have the pack downloaded to do that.

**Comment by Mitchell5200** [comment]
No, the other three dot menu up next to "Create Custom Profile"

**Comment by Santereva** [comment]
> No, the other three dot menu up next to "Create Custom Profile"

Even if I do that, that doesn't fix the fact that I can't download the mod pack and that the manual download comes with everything but the mods.

**Comment by Santereva** [comment]
Would like to say that the download works now, no longer having a problem.
